# Maintainer: Tage Johansson <tage.j@posteo.net>
#
# Generated by aur-fd-scripts - https://git.respiranto.de/aur-fd-scripts.git/

_lang=epo-eng
_pkgname="dict-freedict-${_lang}"
pkgname="${_pkgname}-bin"
_pkgver=1.0.1
pkgver="${_pkgver//-/_}"
pkgrel=1
pkgdesc="Esperanto -> English dictionary for dictd et al. from FreeDict.org"
arch=('any')
url="https://freedict.org/"
license=('GPL' 'AGPL3')
optdepends=('dictd: dict client and server')
provides=("${_pkgname}=${pkgver}")
conflicts=("$_pkgname")
install="${pkgname}.install"
source=("https://download.freedict.org/dictionaries/${_lang}/${_pkgver}/freedict-${_lang}-${_pkgver}.dictd.tar.xz")
sha512sums=('ce7e496925a21a8ed8f3a44ef689c4b1817df476fc4c7fe376eeab4b74d6c8f2fcec6b1eeee4cadb8909621d2649b7c09a1a95b1c131f0b593c11211c3f86366')

package()
{
	install -m 755 -d "${pkgdir}/usr/share/dictd"
	install -m 644 -t "${pkgdir}/usr/share/dictd/" \
		"${_lang}/${_lang}".{dict.dz,index}

	for file in "$_lang"/{AUTHORS,README,NEWS,ChangeLog}
	do
		if test -f "$file"
		then
			install -m 644 -Dt "${pkgdir}/usr/share/doc/freedict/${_lang}/" "$file"
		fi
	done
}
